"""Framework-neutral service boundary for interactive simulation clients."""

from .backend import (
    BackendAgent,
    BackendFrame,
    BackendManifest,
    PythonSimulationBackend,
    SimulationBackend,
    SimulationBackendFactory,
    python_backend_factory,
)
from .contracts import (
    AGENT_DETAIL_KIND,
    AGENT_DETAIL_SCHEMA_VERSION,
    FRAME_SCHEMA_VERSION,
    MANIFEST_SCHEMA_VERSION,
    PROTOCOL_VERSION,
    RENDER_FRAME_KIND,
    RUN_MANIFEST_KIND,
    RUN_STATUS_FAILED,
    RUN_STATUS_PAUSED,
    RUN_STATUS_STEPPING,
    AgentDetail,
    RenderFrame,
    RunManifest,
)
from .sessions import (
    AgentNotFoundError,
    DuplicateRunError,
    RunDefinition,
    RunFailedError,
    RunManager,
    RunNotFoundError,
    RunServiceError,
    RunSession,
)

__all__ = [
    "AGENT_DETAIL_KIND",
    "AGENT_DETAIL_SCHEMA_VERSION",
    "AgentDetail",
    "AgentNotFoundError",
    "BackendAgent",
    "BackendFrame",
    "BackendManifest",
    "DuplicateRunError",
    "FRAME_SCHEMA_VERSION",
    "MANIFEST_SCHEMA_VERSION",
    "PROTOCOL_VERSION",
    "PythonSimulationBackend",
    "RENDER_FRAME_KIND",
    "RUN_MANIFEST_KIND",
    "RUN_STATUS_FAILED",
    "RUN_STATUS_PAUSED",
    "RUN_STATUS_STEPPING",
    "RenderFrame",
    "RunDefinition",
    "RunFailedError",
    "RunManager",
    "RunManifest",
    "RunNotFoundError",
    "RunServiceError",
    "RunSession",
    "SimulationBackend",
    "SimulationBackendFactory",
    "python_backend_factory",
]
